### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by lemorlenny** [surya-veer/RealTime-DigitRecognition#6]
after terminate to track any symbol I receive this:

  File "D:\Project_Python\RealtimeDigitRecon\RealTime-DigitRecognition-master\RealTime-DigitRecognition-master\process_image.py", line 59, in get_output_image
    im2,contours,hierarchy = cv2.findContours(thresh, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

Python 3.7.1
Keras 2.0.8
Pygame 1.9.6

Best regards

**Comment by surya-veer** [comment]
This problem is because of OpenCv version, you can now use:
contours,hierarchy = cv2.findContours(thresh, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

**Comment by AadhithyanKarthick** [comment]
After changing the code to contours,hierarchy = cv2.findContours(thresh, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

I got the below error

Traceback (most recent call last):
  File "app.py", line 86, in <module>
    output_img = get_output_image(fname)  #error
  File "D:\RealTime-DigitRecognition-master\RealTime-DigitRecognition-master\process_image.py", line 80, in get_output_image
    pred = predict_digit(roi)
  File "D:\RealTime-DigitRecognition-master\RealTime-DigitRecognition-master\process_image.py", line 14, in predict_digit
    image = img.cast(test_image, img.float32)
AttributeError: 'numpy.ndarray' object has no attribute 'cast'

**Comment by AadhithyanKarthick** [comment]
Traceback (most recent call last):
  File "app.py", line 86, in <module>
    output_img = get_output_image(fname)
  File "K:\RealTime-DigitRecognition-master\RealTime-DigitRecognition-master\process_image.py", line 80, in get_output_image
    pred = predict_digit(roi)
  File "K:\RealTime-DigitRecognition-master\RealTime-DigitRecognition-master\process_image.py", line 14, in predict_digit
    return np.argmax(model.predict(test_image))

TypeError: Value passed to parameter 'input' has DataType uint8 not in list of allowed values: float16, bfloat16, float32, float64

I am getting this error after changing the code as below mentioned
contours,hierarchy = cv2.findContours(thresh, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

**Comment by tauthichmi1307** [comment]
hello surya-veer!!!
I run into a small error that is no module named 'process_image'
Can you help me!

**Comment by djxhpc** [comment]
Hello Surya-veer 
 How to fix the problem?
File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 325, in class_and_config_for_serialized_keras_object
    for key, item in cls_config.items():

**AttributeError: 'list' object has no attribute 'items'**

Thank you!!!
